personnelapp/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Static pages
use App\Model\Project;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('/about', function () {
    return view('static_pages.about');
})->name('about');


//Authentification
Auth::routes();
Route::get('/home', 'HomeController@index')->name('user.dashboard');
Route::get('/users/logout', 'Auth\LoginController@userlogout')->name('user.logout');

//Project table CRUD with resources
Route::resource('users', 'UserController');


//Admin authentification
Route::prefix('admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/home', 'AdminController@index')->name('admin.dashboard');
    Route::get('/register', 'Auth\Admin\AdminRegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'Auth\Admin\AdminRegisterController@register')->name('admin.register');
    Route::get('/login', 'Auth\Admin\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\Admin\AdminLoginController@login')->name('admin.login');
    Route::get('/logout', 'Auth\Admin\AdminLoginController@logout')->name('admin.logout');
    // Password reset routes
    Route::post('/password/email', 'Auth\Admin\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::post('/password/reset', 'Auth\Admin\AdminForgotPasswordController@reset')->name('admin.password.update');
    Route::get('/password/reset', 'Auth\Admin\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::get('/password/reset/{token}', 'Auth\Admin\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
});

// Other way to do admin route !!
//Route::get('admin/dashboard','AdminController@index');
//Route::get('admin','Admin\LoginController@showLoginForm')->name('admin.login');
//Route::post('admin','Admin\LoginController@login');
//Route::post('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
//Route::get('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
//Route::post('admin-password/reset','Admin\ResetPasswordController@reset');
//Route::get('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
//
//


### Search route
Route::get('/search','HomeController@search');

//Project table Route
Route::prefix('admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/home', 'AdminController@index')->name('admin.dashboard');
    Route::get('/register', 'Auth\Admin\AdminRegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'Auth\Admin\AdminRegisterController@register')->name('admin.register');
    Route::get('/login', 'Auth\Admin\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\Admin\AdminLoginController@login')->name('admin.login');
    Route::get('/logout', 'Auth\Admin\AdminLoginController@logout')->name('admin.logout');
    // Password reset routes
    Route::post('/password/email', 'Auth\Admin\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::post('/password/reset', 'Auth\Admin\AdminForgotPasswordController@reset')->name('admin.password.update');
    Route::get('/password/reset', 'Auth\Admin\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::get('/password/reset/{token}', 'Auth\Admin\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

});

Route::get('/api/projects', function() {
    // If the Content-Type and Accept headers are set to 'application/json',
    // this will return a JSON structure. This will be cleaned up later.
    return Project::paginate(10);
});

Route::get('project/{id}', function($id) {
    return Project::find($id);
});

Route::post('projects', function(Request $request) {
    return Project::create($request->all);
});

Route::put('projects/{id}', function(Request $request, $id) {
    $user = Project::findOrFail($id);
    $user->update($request->all());

    return $user;
});

Route::delete('project/{id}', function($id) {
    Project::destroy($id);

    return 204;
});

personnelapp/app/User.php
<?php

namespace App;


use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Scout\Searchable;

class User extends Authenticatable
{
    use Notifiable,Searchable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function searchableAs()
    {
        return 'name';
    }
}

personnelapp/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::paginate(15);;
        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update(['name'=>$request->name,'email'=>$request->email]);
        return redirect(route('users.index'))->with('message', 'Modifié avec succée');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {


        $user->delete();
        return redirect(route('users.index'))->with('message', 'Supprimé avec succée');




    }
}

personnelapp/resources/views/users/edit.blade.php
@extends('layouts.app')
@if(Auth::guard('admin')->check())
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Modifier un utilisateur</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('users.update', [$user]) }}">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Nom</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">E-Mail</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Enregistrer
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif

personnelapp/resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')

    @if(Auth::guard('admin')->check())
        <div class="container">
            <div class="card">
                <div class="card card-header-contrast">
                    Gestion des Utilisateurs
                </div>
                <div class="card-body">


                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Date of creation</th>
                                <th colspan="3">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($users as $user)
                                @php
                                @endphp
                                <tr>
                                    <td>{{$user->id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td> {{ $user->created_at->format('Y-m-d') }}</td>
                                    <td><a href="{{action('UserController@edit', $user->id)}}" class="btn btn-warning">Edit</a></td>
                                    <td><a href="{{action('UserController@show', $user->id)}}" class="btn btn-info">Show</a></td>
                                    <td>
                                        <form action="{{action('UserController@destroy', $user->id)}}" method="post">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    {{ $users->links() }}


                </div>


        </div>
    @else
        <p class="text-danger">
            Veuillez vous connecter <a href="{{route('admin.login')}}">Ici</a>
        </p>
    @endif

    @stop

personnelapp/resources/views/users/show.blade.php
@extends('layouts.app')
@if(Auth::guard('admin')->check())
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Vusialiser un utilisateur</div>
                    <div class="panel-body">
                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Nom</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">E-Mail</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required>
                                </div>
                            </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endif